#!/usr/bin/env bash

notify-send "Getting list of available Wi-Fi networks..."
# Get a list of available wifi connections and morph it into a nice-looking list
wifi_list=$(nmcli --fields "SECURITY,SSID" device wifi list | sed 1d | sed 's/  */ /g' | sed -E "s/WPA*.?\S/ /g" | sed "s/^--/ /g" | sed "s/  //g" | sed "/--/d")

connected=$(nmcli -fields WIFI g)
if [[ "$connected" =~ "enabled" ]]; then
	toggle="󰖪  Disable Wi-Fi"
elif [[ "$connected" =~ "disabled" ]]; then
	toggle="󰖩  Enable Wi-Fi"
fi

# Check if all hardware is rfkilled, and offer airplane mode options
if rfkill -o SOFT | grep "unblocked" ; then
	airplane="✈ Enable Airplane Mode"
	hidden=" Hidden Network"
	list="$toggle\n$airplane\n$wifi_list\n$hidden"
else
	airplane="✈ Disable Airplane Mode"
	list="$airplane"
fi

# Use rofi to select wifi network
chosen_network=$(echo -e "$list" | uniq -u | rofi -dmenu -i -selected-row 1 -p "Wi-Fi SSID: " )
# Get name of connection
read -r chosen_id <<< "${chosen_network:3}"

if [ "$chosen_network" = "" ]; then
	exit
elif [ "$chosen_network" = "✈ Enable Airplane Mode" ]; then
	rfkill block all
elif [ "$chosen_network" = "✈ Disable Airplane Mode" ]; then
	rfkill unblock all
elif [ "$chosen_network" = "󰖩  Enable Wi-Fi" ]; then
	nmcli radio wifi on
elif [ "$chosen_network" = "󰖪  Disable Wi-Fi" ]; then
	nmcli radio wifi off
else
	# Message to show when connection is activated successfully
  	success_message="You are now connected to the Wi-Fi network \"$chosen_id\"."
	# Get saved connections
	saved_connections=$(nmcli -g NAME connection)
	if [[ $(echo "$saved_connections" | grep -w "$chosen_id") = "$chosen_id" ]]; then
		nmcli connection up id "$chosen_id" | grep "successfully" && notify-send "Connection Established" "$success_message"
	else
		if [ "$chosen_network" = " Hidden Network" ]; then
			chosen_id=$(rofi -dmenu -p "Wi-Fi SSID: " )
		fi
		if [[ "$chosen_network" =~ "" ]]; then
			wifi_password=$(rofi -dmenu -p "Password: " )
		fi
		if [ "$chosen_network" = " Hidden Network" ]; then
			nmcli device wifi connect "$chosen_id" password "$wifi_password" hidden yes | grep "successfully" && notify-send "Connection Established" "$success_message"
		else
			nmcli device wifi connect "$chosen_id" password "$wifi_password" | grep "successfully" && notify-send "Connection Established" "$success_message"
		fi
  fi
fi
